/* GENERATED by scripts/build_report_data.py — do not edit by hand.
   Every figure is read from data/*.csv. Re-run the script after any data change. */
window.REPORT_DATA = {
 "meta": {
  "generated": "2026-09-09 22:46",
  "products_total": 241,
  "products_collab": 231,
  "products_base": 10,
  "partners": 94,
  "companies": 77,
  "financials": 132,
  "sources": 424,
  "gaps": 78,
  "jp_priced": 129,
  "date_month": 103,
  "date_month_pct": 43,
  "date_any": 122,
  "date_any_pct": 51,
  "date_coverage_pct": 43,
  "voice_min": 7,
  "voice_min_who": "Universal Music (TOoKA BASE)",
  "voice_max": 370,
  "voice_max_who": "AVIOT",
  "voice_n": 26,
  "brands": 17
 },
 "sku": [
  {
   "b": "AVIOT",
   "n": 80
  },
  {
   "b": "ONKYO",
   "n": 45
  },
  {
   "b": "环球音乐 TOoKA BASE",
   "n": 27
  },
  {
   "b": "Zeeny",
   "n": 26
  },
  {
   "b": "MOONDROP 水月雨",
   "n": 17
  },
  {
   "b": "final / ag",
   "n": 14
  },
  {
   "b": "Sony 索尼",
   "n": 5
  },
  {
   "b": "Victor / JVCKenwood",
   "n": 4
  },
  {
   "b": "SONGX",
   "n": 3
  },
  {
   "b": "Taito / Cafereo",
   "n": 2
  },
  {
   "b": "Hi-Unit",
   "n": 2
  },
  {
   "b": "Owltech",
   "n": 1
  },
  {
   "b": "intime",
   "n": 1
  },
  {
   "b": "猫耳FM MissEvan",
   "n": 1
  },
  {
   "b": "qdc",
   "n": 1
  },
  {
   "b": "星海贝",
   "n": 1
  },
  {
   "b": "LUKLUK",
   "n": 1
  }
 ],
 "prices": [
  2980.0,
  5400.0,
  5980.0,
  5980.0,
  5980.0,
  7150.0,
  7150.0,
  7150.0,
  7150.0,
  7920.0,
  8200.0,
  8200.0,
  9800.0,
  9980.0,
  10800.0,
  12100.0,
  12100.0,
  12100.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14300.0,
  14800.0,
  15400.0,
  15950.0,
  17050.0,
  17050.0,
  17600.0,
  17600.0,
  17600.0,
  17930.0,
  18000.0,
  18000.0,
  18000.0,
  18000.0,
  18700.0,
  18700.0,
  18700.0,
  18700.0,
  18700.0,
  18700.0,
  18700.0,
  19800.0,
  19800.0,
  19800.0,
  19800.0,
  19800.0,
  19800.0,
  19800.0,
  19800.0,
  19800.0,
  19800.0,
  19800.0,
  19800.0,
  20000.0,
  20000.0,
  20000.0,
  20000.0,
  20000.0,
  22000.0,
  22000.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  22880.0,
  25960.0,
  27500.0,
  39660.0,
  43800.0,
  46260.0,
  49500.0,
  93300.0,
  104500.0,
  143000.0,
  143000.0,
  153800.0,
  181500.0,
  250000.0
 ],
 "premium": [
  {
   "p": "TE-Q3R",
   "base": 10791.0,
   "collab": 18700.0,
   "pct": 73.3,
   "note": "廉价平台",
   "n": 1
  },
  {
   "p": "TE-Q3R",
   "base": 10791.0,
   "collab": 22880.0,
   "pct": 112.0,
   "note": "廉价平台",
   "n": 2
  },
  {
   "p": "TE-V1R",
   "base": 14355.0,
   "collab": 18700.0,
   "pct": 30.3,
   "note": "主力平台 · 最多 SKU 共用",
   "n": 4
  },
  {
   "p": "TE-V1R",
   "base": 14355.0,
   "collab": 22880.0,
   "pct": 59.4,
   "note": "主力平台 · 最多 SKU 共用",
   "n": 29
  },
  {
   "p": "TE-J2",
   "base": 29700.0,
   "collab": 39660.0,
   "pct": 33.5,
   "note": "旗舰入耳 · HYDE",
   "n": 1
  },
  {
   "p": "WA-J1",
   "base": 35640.0,
   "collab": 46260.0,
   "pct": 29.8,
   "note": "旗舰头戴 · HYDE",
   "n": 1
  },
  {
   "p": "WB-P1",
   "base": 14355.0,
   "collab": 17930.0,
   "pct": 24.9,
   "note": "骨传导",
   "n": 1
  }
 ],
 "premium_cn": {
  "p": "MOONDROP RAYS",
  "base": 399.0,
  "collab": 439.0,
  "pct": 10.0,
  "note": "中国 · 电竞俱乐部联名",
  "cur": "CNY"
 },
 "vol": [
  {
   "l": "ag COTSUBU 帕特拉二弹 · 年内配额售罄",
   "v": 25000,
   "t": "一手已披露",
   "s": "news.yahoo.co.jp"
  },
  {
   "l": "ag COTSUBU 帕特拉二弹 · 开售 12 小时",
   "v": 10000,
   "t": "一手已披露",
   "s": "prtimes.jp"
  },
  {
   "l": "final ASMR／睡眠向累计",
   "v": 300000,
   "t": "一手已披露",
   "s": "prtimes.jp"
  },
  {
   "l": "AVIOT Q 系列平台累计",
   "v": 370000,
   "t": "二手已披露",
   "s": "www.phileweb.com"
  },
  {
   "l": "ONKYO 年度受注量 2025",
   "v": 100000,
   "t": "一手已披露",
   "s": "www.dreamnews.jp"
  },
  {
   "l": "KPro01 众筹支持人数",
   "v": 10003,
   "t": "二手已披露",
   "s": "news.mynavi.jp"
  },
  {
   "l": "MOONDROP 知更鸟 · 三平台合计",
   "v": 20000,
   "t": "六级信源",
   "s": "m.hupu.com"
  },
  {
   "l": "ag COTSUBU 帕特拉一弹 · 最终再版",
   "v": 1000,
   "t": "二手已披露",
   "s": "panora.tokyo"
  },
  {
   "l": "ag COTSUBU 帕特拉一弹 · 见面会配额",
   "v": 400,
   "t": "二手已披露",
   "s": "av.watch.impress.co.jp"
  },
  {
   "l": "AVIOT TE-D01v 平台累计",
   "v": 120000,
   "t": "一手已披露",
   "s": "aviot.jp"
  }
 ],
 "partner": [
  {
   "c": "声优 · 个人",
   "n": 42,
   "raw": "seiyuu_individual"
  },
  {
   "c": "虚拟艺人 · 个人",
   "n": 21,
   "raw": "vtuber_individual"
  },
  {
   "c": "虚拟艺人 · 组合",
   "n": 6,
   "raw": "vtuber_unit"
  },
  {
   "c": "音乐人",
   "n": 5,
   "raw": "musician"
  },
  {
   "c": "虚拟角色",
   "n": 3,
   "raw": "virtual_character"
  },
  {
   "c": "虚拟歌手／声库",
   "n": 3,
   "raw": "virtual_singer"
  },
  {
   "c": "声优 · 团体",
   "n": 2,
   "raw": "seiyuu_group"
  },
  {
   "c": "广播节目",
   "n": 2,
   "raw": "radio_programme"
  },
  {
   "c": "插画师兼 VTuber",
   "n": 1,
   "raw": "illustrator_vtuber"
  },
  {
   "c": "声优厂牌",
   "n": 1,
   "raw": "seiyuu_label"
  },
  {
   "c": "唱见",
   "n": 1,
   "raw": "utaite_individual"
  },
  {
   "c": "艺人／搞笑艺人",
   "n": 1,
   "raw": "celebrity_comedian"
  },
  {
   "c": "电竞俱乐部",
   "n": 1,
   "raw": "esports_club"
  },
  {
   "c": "电视节目 IP",
   "n": 1,
   "raw": "tv_programme_ip"
  },
  {
   "c": "评测人／影响者",
   "n": 1,
   "raw": "reviewer_influencer"
  },
  {
   "c": "母带工程师",
   "n": 1,
   "raw": "mastering_engineer"
  },
  {
   "c": "音响监督",
   "n": 1,
   "raw": "sound_director"
  },
  {
   "c": "电视台播音员",
   "n": 1,
   "raw": "tv_announcer"
  }
 ],
 "voice": [
  {
   "n": 7,
   "p": 17050,
   "l": "TRUE WIRELESS STEREO EARPHONES D60A"
  },
  {
   "n": 7,
   "p": 17050,
   "l": "TRUE WIRELESS STEREO EARPHONES diamond-cut"
  },
  {
   "n": 8,
   "p": 10800,
   "l": "ZE500 for ASMR CyberPatra"
  },
  {
   "n": 11,
   "p": 20000,
   "l": "ANIMA AOW01 Girls Band Cry Diamond Dust"
  },
  {
   "n": 11,
   "p": 18000,
   "l": "ANIMA AOW04 Koyanagi Rou model"
  },
  {
   "n": 11,
   "p": 18000,
   "l": "ANIMA AOW04 Hoshidou Shou model"
  },
  {
   "n": 11,
   "p": 22000,
   "l": "GochiUsa AOW01 MARKII collab model"
  },
  {
   "n": 13,
   "p": 20000,
   "l": "Saionji Mary collab model"
  },
  {
   "n": 14,
   "p": 8200,
   "l": "COTSUBU for ASMR Patra Edition -BLACK Ver.-"
  },
  {
   "n": 15,
   "p": 20000,
   "l": "Angel Next Door ANIMA AOW01 collab model"
  },
  {
   "n": 24,
   "p": 17930,
   "l": "Nakayama Kinni-kun collab bone conduction"
  },
  {
   "n": 39,
   "p": 22000,
   "l": "Kiramune collab model"
  },
  {
   "n": 100,
   "p": 22880,
   "l": "Azur Lane 2nd wave collab model"
  },
  {
   "n": 140,
   "p": 18700,
   "l": "Marimari Marry collab model"
  },
  {
   "n": 150,
   "p": 22880,
   "l": "BUSTAFELLOWS collab model"
  },
  {
   "n": 200,
   "p": 22880,
   "l": "hololive English -Myth- collab model"
  },
  {
   "n": 220,
   "p": 22880,
   "l": "Oshi no Ko collab model"
  },
  {
   "n": 250,
   "p": 22880,
   "l": "New Panty & Stocking collab model"
  },
  {
   "n": 370,
   "p": 22880,
   "l": "hololive English -Advent- collab model"
  }
 ],
 "ladder": [
  {
   "c": "万代南梦宫控股",
   "v": 1348246,
   "k": "ip",
   "period": "FY2026/3",
   "yoy": 8.6
  },
  {
   "c": "日本电视台控股",
   "v": 484400,
   "k": "ip",
   "period": "FY2026/3",
   "yoy": 4.9
  },
  {
   "c": "史克威尔艾尼克斯控股",
   "v": 297661,
   "k": "ip",
   "period": "FY2026/3",
   "yoy": -8.3
  },
  {
   "c": "KADOKAWA",
   "v": 282908,
   "k": "ip",
   "period": "FY2026/3",
   "yoy": 1.8
  },
  {
   "c": "集英社",
   "v": 228954,
   "k": "ip",
   "period": "85th term FY2026/5",
   "yoy": -0.1
  },
  {
   "c": "Aniplex",
   "v": 211595,
   "k": "ip",
   "period": "FY2026/3",
   "yoy": 45.1
  },
  {
   "c": "东映",
   "v": 185333,
   "k": "ip",
   "period": "FY2026/3",
   "yoy": 3.0
  },
  {
   "c": "讲谈社",
   "v": 169169,
   "k": "ip",
   "period": "87th term FY2025/11",
   "yoy": -1.1
  },
  {
   "c": "小学馆",
   "v": 103567,
   "k": "ip",
   "period": "88th term FY2026/2",
   "yoy": -5.5
  },
  {
   "c": "东映动画",
   "v": 93600,
   "k": "ip",
   "period": "FY2026/3",
   "yoy": 6.4
  },
  {
   "c": "Taito",
   "v": 72944,
   "k": "ip",
   "period": "FY2026/3",
   "yoy": 1.7
  },
  {
   "c": "ANYCOLOR",
   "v": 55681,
   "k": "ip",
   "period": "FY2026/4",
   "yoy": 29.9
  },
  {
   "c": "viviON 集团",
   "v": 52900,
   "k": "ip",
   "period": "FY2023",
   "yoy": 16.5
  },
  {
   "c": "三丽鸥",
   "v": 52000,
   "k": "ip",
   "period": "FY2027/3 Q1",
   "yoy": null
  },
  {
   "c": "円谷制作",
   "v": 13870,
   "k": "ip",
   "period": "FY2026/3",
   "yoy": -15.4
  },
  {
   "c": "Adways",
   "v": 11800,
   "k": "ip",
   "period": "FY2026/12",
   "yoy": -3.4
  },
  {
   "c": "COVER",
   "v": 8825,
   "k": "ip",
   "period": "FY2027/3 Q1",
   "yoy": -8.3
  },
  {
   "c": "Broccoli",
   "v": 5975,
   "k": "ip",
   "period": "FY2019/2 reference",
   "yoy": 10.4
  },
  {
   "c": "Nitroplus",
   "v": 4000,
   "k": "ip",
   "period": "FY2023/8",
   "yoy": null
  },
  {
   "c": "ONKYO 联名品类（推导中值）",
   "v": 2000,
   "k": "audio",
   "period": "2025",
   "yoy": null
  }
 ],
 "disclose": [
  {
   "c": "东映动画 · 版权事业分部",
   "v": 48905,
   "pct": 52,
   "d": 1
  },
  {
   "c": "讲谈社 · 权利收入",
   "v": 28540,
   "pct": null,
   "d": 1
  },
  {
   "c": "小学馆 · 版权收入等",
   "v": 15729,
   "pct": null,
   "d": 1
  },
  {
   "c": "COVER · 授权／联动",
   "v": 7198,
   "pct": 14.6,
   "d": 1
  },
  {
   "c": "集英社 · 事业收入（与物贩合并）",
   "v": 110000,
   "pct": null,
   "d": 2
  },
  {
   "c": "ANYCOLOR · 无授权科目",
   "v": 0,
   "pct": null,
   "d": 0
  }
 ],
 "seiyuu": [
  {
   "y": 2001,
   "f": 225.0,
   "m": 145.0
  },
  {
   "y": 2004,
   "f": 438.0,
   "m": null
  },
  {
   "y": 2008,
   "f": 535.0,
   "m": null
  },
  {
   "y": 2014,
   "f": 644.0,
   "m": null
  },
  {
   "y": 2016,
   "f": 728.0,
   "m": null
  },
  {
   "y": 2018,
   "f": 800.0,
   "m": null
  },
  {
   "y": 2019,
   "f": 847.0,
   "m": null
  },
  {
   "y": 2020,
   "f": 907.0,
   "m": null
  },
  {
   "y": 2021,
   "f": 955.0,
   "m": null
  },
  {
   "y": 2022,
   "f": 1003.0,
   "m": null
  },
  {
   "y": 2023,
   "f": 1039.0,
   "m": null
  },
  {
   "y": 2024,
   "f": 1063.0,
   "m": null
  },
  {
   "y": 2025,
   "f": 1099.0,
   "m": null
  },
  {
   "y": 2026,
   "f": 1135.0,
   "m": 702.0
  }
 ],
 "cnmkt": [
  {
   "y": "2024",
   "u": 2.18,
   "v": 428.0,
   "asp": 196.0
  },
  {
   "y": "2025",
   "u": 2.03,
   "v": 452.0,
   "asp": 223.0
  },
  {
   "y": "2026F",
   "u": 1.99,
   "v": null,
   "asp": null
  }
 ],
 "band": [
  {
   "b": "0–100 元",
   "vol": null,
   "val": null,
   "dir": -1,
   "note": "下降"
  },
  {
   "b": "100–200 元",
   "vol": null,
   "val": null,
   "dir": -1,
   "note": "下降"
  },
  {
   "b": "200–300 元",
   "vol": 30.0,
   "val": 30.0,
   "dir": 1,
   "note": "增长"
  },
  {
   "b": "300–500 元",
   "vol": null,
   "val": null,
   "dir": 1,
   "note": "两位数增长 数值未披露"
  },
  {
   "b": "500–1000 元",
   "vol": 33.0,
   "val": 30.0,
   "dir": 1,
   "note": "增长"
  },
  {
   "b": "1000–1500 元",
   "vol": 40.0,
   "val": 42.0,
   "dir": 1,
   "note": "增长"
  },
  {
   "b": "1500–2000 元",
   "vol": null,
   "val": null,
   "dir": 1,
   "note": "两位数增长 数值未披露"
  },
  {
   "b": "2000 元以上",
   "vol": null,
   "val": null,
   "dir": 1,
   "note": "两位数增长 数值未披露"
  }
 ],
 "form": [
  {
   "f": "真无线 TWS",
   "v": 7721.0,
   "g": 6.7
  },
  {
   "f": "开放式 OWS",
   "v": 2996.0,
   "g": 20.2
  },
  {
   "f": "头戴式",
   "v": 878.0,
   "g": 26.3
  }
 ],
 "jpband": [
  {
   "b": "1 万日元以下",
   "v": 40.0
  },
  {
   "b": "1–2 万日元",
   "v": 20.0
  },
  {
   "b": "2 万日元以上",
   "v": 40.0
  }
 ],
 "demo": [
  {
   "k": "31–40 岁",
   "v": 40.01
  },
  {
   "k": "更年轻群体",
   "v": 31.63
  },
  {
   "k": "其他",
   "v": 28.36
  }
 ],
 "demo_extra": {
  "female": 51.97,
  "male": 48.03,
  "use5h": 38.38
 },
 "pv": [
  {
   "s": "アニメイトタイムズ",
   "pv": 2416.0,
   "uu": 1069.0,
   "pv_alt": 2818.0,
   "uu_alt": 1214.0,
   "tw": 670000.0,
   "a2534": 31.0
  }
 ],
 "cert": [
  {
   "c": "中国 SRRC 型号核准",
   "w": 8.0,
   "note": "含测试全流程约8周 有效期5年 现行不收费",
   "k": "cn"
  },
  {
   "c": "中国 CCC / 3C",
   "w": 5.0,
   "note": "4-6周 最多两个月",
   "k": "cn"
  },
  {
   "c": "日本 技適 工事設計認証",
   "w": 4.0,
   "note": "有案例约1个月 需无线测试样机 TELEC等登录机关",
   "k": "jp"
  },
  {
   "c": "日本 PSE（充电盒）",
   "w": 0.0,
   "note": "自2019-02-01起为强制前提 非周期项",
   "k": "jp"
  }
 ],
 "resale": {
  "deals": 5,
  "avg": 11883
 },
 "photobook": [
  {
   "k": "佐倉綾音",
   "v": 10712,
   "note": "Oricon 累计口径 女性声优写真集第一"
  },
  {
   "k": "水樹奈々",
   "v": 5664,
   "note": "Oricon 累计口径 第二"
  },
  {
   "k": "生田絵梨花_对照",
   "v": 178688,
   "note": "顶级偶像写真集首周 量级对照"
  }
 ],
 "risk": [
  {
   "d": "2018-06",
   "l": "『二度目の人生を異世界で』四声优",
   "sev": 5,
   "sevl": "项目终止",
   "x": "动画中止播出与制作 + 18卷小说停止出货并自主回收",
   "trg": "原作者过往仇恨言论",
   "collab": true,
   "note": "同日同时下车 增田俊樹 安野希世乃 中島愛 山下七海。增田与安野均已有耳机联名产品"
  },
  {
   "d": "2019",
   "l": "朴璐美 · 置鮎龍太郎",
   "sev": 2,
   "sevl": "言论争议",
   "x": "遭中文互联网抵制",
   "trg": "涉香港议题言论",
   "collab": false,
   "note": "后续商业后果未在信源中量化"
  },
  {
   "d": "2020-09",
   "l": "桐生ココ · 赤井はあと（hololive）",
   "sev": 5,
   "sevl": "项目终止",
   "x": "全体艺人失去bilibili直播权限 两人停止活动 hololive后退出bilibili",
   "trg": "直播显示台湾为国家 + 提及台湾这个国家",
   "collab": false,
   "note": "双向风险唯一完整样本 COVER的一个中国表述随即在台湾与日本引发第二轮反弹"
  },
  {
   "d": "2021-02",
   "l": "茅野愛衣",
   "sev": 4,
   "sevl": "多作品下架",
   "x": "事务所致歉",
   "trg": "个人广播中提及参拜靖国神社",
   "collab": true,
   "note": "已有环球音乐TOoKA BASE耳机联名SKU P0081"
  },
  {
   "d": "2021-06",
   "l": "茅野愛衣",
   "sev": 4,
   "sevl": "多作品下架",
   "x": "明日方舟 崩坏学园 阴阳师 永远的七日之都 陆续下架替换",
   "trg": "同上 后续处置",
   "collab": true,
   "note": "明日方舟表述为依开发方要求"
  },
  {
   "d": "2021-06",
   "l": "茅野愛衣",
   "sev": 4,
   "sevl": "多作品下架",
   "x": "碧蓝航线国服移除其配音七艘舰船全部语音 未事先通知",
   "trg": "同上 后续处置",
   "collab": true,
   "note": "含爱宕 加贺 声望 齐柏林伯爵"
  },
  {
   "d": "2021",
   "l": "本渡楓 · 桑原由気",
   "sev": 2,
   "sevl": "言论争议",
   "x": "舆论争议",
   "trg": "靖国神社与军国主义人物塑像合影",
   "collab": false,
   "note": "本渡楓另在广播中自述为东乡平八郎后裔"
  },
  {
   "d": "2025-02",
   "l": "BanG Dream! 系列一位女声优",
   "sev": 2,
   "sevl": "言论争议",
   "x": "在中国引发大规模争议",
   "trg": "使用台湾旗帜",
   "collab": false,
   "note": "具体姓名在所获信源中未标明"
  },
  {
   "d": "2025-03",
   "l": "森久保祥太郎",
   "sev": 3,
   "sevl": "角色替换",
   "x": "在一款中国游戏被替换掉三个角色 未获任何说明",
   "trg": "未说明",
   "collab": true,
   "note": "已有环球音乐TOoKA BASE耳机联名SKU P0169。据报由寺岛惇太接替"
  },
  {
   "d": "2025-09",
   "l": "『鸣潮』中文配音",
   "sev": 3,
   "sevl": "角色替换",
   "x": "官方宣布更换女主角普通话配音",
   "trg": "配音演员言论争议",
   "collab": false,
   "note": "鸣潮为MOONDROP联名对象 U.C.T.S."
  },
  {
   "d": "2025-12",
   "l": "日本艺人整体",
   "sev": 5,
   "sevl": "项目终止",
   "x": "在华演出接连取消 中方发布旅行提示",
   "trg": "首相高市早苗涉台言论",
   "collab": false,
   "note": "记录中首次触发点既非艺人本人亦非作品而是日本政府 任何筛选流程都无法覆盖"
  },
  {
   "d": "2026-03",
   "l": "佐藤拓也",
   "sev": 3,
   "sevl": "角色替换",
   "x": "自恋与深空Rey与明日方舟Midnight下车",
   "trg": "过往发言 另有17年前靖国参拜报道",
   "collab": false,
   "note": "另见 https://c.m.163.com/news/a/KN8E4QM7051486RA.html"
  }
 ],
 "cadence": [
  {
   "m": "2025-09",
   "a": 0,
   "o": 1
  },
  {
   "m": "2025-10",
   "a": 0,
   "o": 1
  },
  {
   "m": "2025-11",
   "a": 4,
   "o": 0
  },
  {
   "m": "2025-12",
   "a": 4,
   "o": 1
  },
  {
   "m": "2026-03",
   "a": 1,
   "o": 0
  },
  {
   "m": "2026-04",
   "a": 2,
   "o": 0
  },
  {
   "m": "2026-05",
   "a": 0,
   "o": 2
  },
  {
   "m": "2026-06",
   "a": 5,
   "o": 1
  },
  {
   "m": "2026-07",
   "a": 2,
   "o": 1
  },
  {
   "m": "2026-08",
   "a": 3,
   "o": 8
  },
  {
   "m": "2026-09",
   "a": 1,
   "o": 3
  }
 ]
};
